
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TOKEN=${TOKEN}
      - CHAT_ID=${CHAT_ID}
    depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway

  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-index:/loki/index
      - ./loki-cache:/loki/cache
      - ./loki-chunks:/loki/chunks
      - ./loki-compactor:/loki/compactor

  promtail:
    image: grafana/promtail:2.9.1
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:9.4.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
