#!/bin/bash

git pull

docker stop steam_activity_bot

docker rm steam_activity_bot

docker build -t steam_activity_bot .

docker run -d \
  --name steam_activity_bot \
  --restart unless-stopped \
  --env-file .env \
  steam_activity_bot
